
def title_im():
    print('''
    
    ▄████████  ▄█   ███▄▄▄▄   ████████▄     ▄████████    ▄████████ 
    ███    ███ ███  ███▀▀▀██▄ ███   ▀███   ███    ███   ███    ███ 
    ███    █▀  ███▌ ███   ███ ███    ███   ███    █▀    ███    ███ 
    ▄███▄▄▄    ███▌ ███   ███ ███    ███  ▄███▄▄▄      ▄███▄▄▄▄██▀ 
    ▀▀███▀▀▀   ███▌ ███   ███ ███    ███ ▀▀███▀▀▀     ▀▀███▀▀▀▀▀   
    ███        ███  ███   ███ ███    ███   ███    █▄  ▀███████████ 
    ███        ███  ███   ███ ███   ▄███   ███    ███   ███    ███ 
    ███        █▀    ▀█   █▀  ████████▀    ██████████   ███    ███ 
                                                        ███    ███ 
    _______________________________________________________________
    

    ██ ███████     ███████  ██████  ██████      ██    ██  ██████  ██    ██ 
    ██ ██          ██      ██    ██ ██   ██      ██  ██  ██    ██ ██    ██ 
    ██ ███████     █████   ██    ██ ██████        ████   ██    ██ ██    ██ 
    ██      ██     ██      ██    ██ ██   ██        ██    ██    ██ ██    ██ 
    ██ ███████     ██       ██████  ██   ██        ██     ██████   ██████  ''')

    
    print(''' 
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNXXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXKKXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKKKKXWMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKKKKKNWMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKKKKKXWMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKKKK0KXWMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX00KKKKNWMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMMMWX00000KXWMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNNMMMMMMMMMMMMMMMWX000000KWMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKKWMMMMMMMMMMMMMMMNK000000KNMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMNK00KNMMMMMMMMMMMMMMWX0000000KNMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMWK0000KNWMMMMMMMMMMMWX00000000KWMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMWX000000KXNWMMMMMMMWNX000000000KWMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMWX0OO0OOO00KXXXXXXKK0O00OO0OO00XWMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMWX0OOOOOOOOOOOOOOOOOOOOOOOOOOO0NMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMN0OOOOOOOOOOOOOOOOOOOOOOOOOOOKWMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMWKOOOOOOOOOOOOOOOOOOOOOOOOOO0NWMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMWX0OOOOOOOOOOOOOOOOOOOOOOOOOKWMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMWMMMMMMMMMMN0OOOOOOOOOOOOOOOOOOOOOOOOOXWMMMMMWWWMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMWNKKXWMMMMMMMMN0OkkOkkkkkkkkkkkkkkkkkkkk0NMMMMMMWKKNWMMMMMMMMMMMMMM
    MMMMMMMMMMMMWX0kkOXWMMMMMMWXOkkkkkkkkkkkkkkkkkkkkkkkkKWMMMMMMWKOOKWWMMMMMMMMMMMM
    MMMMMMMMMMMWKOkkkkO0XNNNNXKOkkkkkkkkkkkkkkkkkkkkkkkkOKWMMMMMMWKkkOKNMMMMMMMMMMMM
    MMMMMMMMMMNKOkkkkkkkOOOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkOXWMMMMMMW0kkkO0NMMMMMMMMMMM
    MMMMMMMMMWKOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0NMMMMMWXOkkkkOKWMMMMMMMMMM
    MMMMMMMMWKOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkO0XWWWNKOkkkkkkOXWMMMMMMMMM
    MMMMMMMMN0kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOO0OOkkkkkkkkk0NMMMMMMMMM
    MMMMMMMWXOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOXWMMMMMMMM
    MMMMMMMWKkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkKWMMMMMMMM
    MMMMMMMN0kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0WMMMMMMMM
    MMMMMMMN0kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0NMMMMMMMM
    MMMMMMMWKkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk0WMMMMMMMM
    MMMMMMMWXkxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkKWMMMMMMMM
    MMMMMMMMNOxxkxxkkkkkkkkkkkkkkkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkkkkONMMMMMMMMM
    MMMMMMMMWKkxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxkxxxkKWMMMMMMMMM
    MMMMMMMMMN0xxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxk0NMMMMMMMMMM
    MMMMMMMMMWNOxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxONMMMMMMMMMMM
    MMMMMMMMMMWXOkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkOXWMMMMMMMMMMM
    MMMMMMMMMMMWN0kxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxk0NWMMMMMMMMMMMM
    MMMMMMMMMMMMMNKOkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxOKNMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMWN0kxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxk0NWMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMWN0kxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxk0NWMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMWNKOkxddxxdddxxxxxxxxxxxxxxxxxxxxddddxxOKNWMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMWNKOkxdddddddddddddddddddddddddxkOKNWWMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMWNXK0OkxddddddddddddddxxkO0KXNWMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNXXKK0000000KKXXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM''')